### PR TITLE
feat(config): add include_routes option to control completion scope

### PR DESCRIPTION
**Pull request by rizkyilhampra**
Hallo. This PR adds a new configuration option `include_routes` that allows to exclude route completions from the search results. 

If you want to know why I created this? That's because I got slow completion when I type `route('`, but I don't think that's an issue for some people, so I don't create issue for it, maybe I just got spec issue :). But I think it would be better to make the scope of completion customizable, in this case the routes.

Here is the changes i made:
- Added new `include_routes` option (defaults to true)
- Modified `get_keyword_pattern` function to filter out route patterns when `include_routes` is false
- Updated README with documentation for the new option

### CODE REVIEW

**Comment by RicardoRamirezR** [comment]
Thank you @rizkyilhampra, it seems ok to me.

These configurations will be global by default. You can make them project-specific by using configuration similar to other Laravel components:

```lua
vim.g.blade_nav = {
  laravel_components = {
    "resources/views/common",
  },
  include_routes = false,
}
```

**Comment by rizkyilhampra** [comment]
@RicardoRamirezR you want me to add more test in checkhealth?

**Comment by RicardoRamirezR** [comment]
@rizkyilhampra looks good, can you double check 
```lua
  if vim.g.blade_nav and not vim.g.blade_nav.include_routes then
  end
```
if `vim.g.blade_nav.include_routes = true` it skips the routes, is that correct?

**Comment by rizkyilhampra** [comment]
@RicardoRamirezR no, when `vim.g.blade_nav.include_routes=true` which also the default, it will keep routes completion, otherwise when false, then skip the routes completion or in other word disable.

**Comment by RicardoRamirezR** [comment]
@rizkyilhampra ahh ok, you're filter them out. Got it.

**Comment by RicardoRamirezR** [comment]
@rizkyilhampra, in the `health` check, it would be possible to report the route inclusion status only if vim.g.blade_nav.include_routes is explicitly defined. This approach would prevent unnecessary health reports for users who haven't configured the route inclusion option.

**Pull request merged**
